create table TM2_LOGMINER_OFFSET
(
	START_TIME	TIMESTAMP,
	RESET_OFFSET	NUMBER(1,0),
	START_SCN	NUMBER(19,0),
	OFFSET_SCN	NUMBER(19,0),
	OFFSET_COMMIT_SCN	NUMBER(19,0),
	OFFSET_ROW_ID	VARCHAR2(18 BYTE),
	KAFKA_STATUS VARCHAR2(30 BYTE),
	LOGMINER_STATUS	VARCHAR2(30 BYTE),
	CONNECT_STATUS VARCHAR2(30),
	UPDATE_TIME	TIMESTAMP,
	PRIMARY KEY (START_TIME)
)
