create table TM2_HEALTH
(
	HEARTBEAT_TIME TIMESTAMP,
	CURRENT_SCN NUMBER(19,0),
	LOGMINER_SCN NUMBER(19,0),
	LOGMINER_RECEIVED TIMESTAMP,
	CONSUMER_RECEIVED TIMESTAMP,
	LOGMINER_CLIENT VARCHAR2(3000),	
	CONSUMER_CLIENT VARCHAR2(3000),
	CPU_UTIL_VALUE NUMBER,
	KAFKA_STATUS VARCHAR2(30),
	LOGMINER_STATUS VARCHAR2(30),
	CONNECT_STATUS VARCHAR2(30),
	ACTIVE_ETL  VARCHAR2(3000),
	STANDBY_ETL  VARCHAR2(3000),
	SERVER_STATUS_UPDATE_TIME TIMESTAMP,
	PRIMARY KEY (HEARTBEAT_TIME)
)
